export { Header } from './Header'
export { Courses } from './courses/Courses'
export { About } from './About'
export { Resume } from './resume/Resume'
export { Projects } from './Projects'
export { NavBar } from './NavBar'
export { Contact } from './contact/Contact'
