name: CI is great
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Deps
        run: npm i
      - name: Cypress run
        uses: cypress-io/github-action@v1
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Deps
        run: npm i
      - name: Build Artifact
        run: npm run build
      - name: Save artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: build
      - name: Save ci assets
        uses: actions/upload-artifact@v1
        with:
          name: ci
          path: ci
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download app
        uses: actions/download-artifact@v1
        with:
          name: app
      - name: Download manifests
        uses: actions/download-artifact@v1
        with:
          name: ci
      - name: CF PUSH
        uses: d3sandoval/cloud-foundry-action@1.1.1
        env:
          CF_TARGET_ORG: dapuzzo
          CF_TARGET_SPACE: development
          CF_USERNAME: ${{ secrets.cfUsername }}
          CF_PASSWORD: ${{ secrets.cfPassword }}
          CF_API: ${{ secrets.cfApi }}
        with:
          args: push -f ci/manifest.yml
