name: CI is great
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Deps
        run: npm i
      - name: Build Artifact
        run: npm run build
      - name: Save artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: build
